### ISSUE TITLE
Clear Caches control panel checkbox disappearing

### ISSUE THREAD

**Issue by askogrand** [ostark/upper#10]
Ill try and append more information to this ticket, but we keep seeing the option to clear our Fastly cache disappear as a checkbox option in the control panel. When we uninstall and reinstall, the option returns, but after a day or two, disappears again.

https://www.dropbox.com/s/ny7onmj94bgo3yw/Screenshot%202018-05-10%2014.29.34.png?dl=0&raw=1

**Comment by askogrand** [comment]
Okay, I have a site with the plugin installed, and the option has disappeared. Should I send you the database dump and composer file?

**Comment by ostark** [comment]
@askogrand a db dump is hopfully not required, but your composer.json/.lock file could be use full.

**Comment by ostark** [comment]
@askogrand any news?

**Comment by askogrand** [comment]
I dont see any logs, or any errors. It doesnt happen locally, only on heroku, so im just going to close it until you have something to work with.
