### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url'

### ISSUE THREAD

**Issue by blasvicco** [ostark/upper#14]
The SQL being executed was:
```MYSQL
INSERT INTO `craft_upper_cache` (`url`, `tags`, `headers`, `siteId`, `dateCreated`, `dateUpdated`, `uid`)...
```

Following [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html):

> The HTTP protocol does not place any a priori limit on the length of a URI. Servers MUST be able to handle the URI of any resource they serve, and SHOULD be able to handle URIs of unbounded length if they provide GET-based forms that could generate such URIs. A server SHOULD return 414 (Request-URI Too Long) status if a URI is longer than the server can handle (see section 10.4.15).

I suggest to update the datatype in the installation (table creation) [here](https://github.com/ostark/upper/blob/7d01348ad0ee8f4db2906f025f93069215aa9bf4/src/migrations/Install.php#L23)

**Comment by ostark** [comment]
Thanks for your suggestion. 
I'll review the changes and create a new migration (instead of changing Install.php).

**Comment by mark-chief** [comment]
This is also happening to me. Exact same error. Best.

**Comment by ostark** [comment]
Thanks again @blasvicco 
Please check @mark-chief 

I hope this migration works for everybody:
https://github.com/ostark/upper/blob/master/src/migrations/m180618_120307_url_index.php

**Comment by blasvicco** [comment]
@ostark I believe my PR is not the best solution because encoding any string length to fixed 32 characters will end up with some collisions. Maybe look for a better hash (more than just 32 characters) or use only the protocol, domain name and path of the request, avoiding the query string. Not sure, but probably with time a better solution will come out.
Regards

**Comment by ostark** [comment]
I thought about the collisions issue as well. Fortunately, we have a try/catch at least.
