### ISSUE TITLE
Multiple installs

### ISSUE THREAD

**Issue by larsboldt** [ostark/upper#18]
We run two sites with each their own Craft installation on the same Varnish server. I think we run into cache invalidation problems because both Craft installations attempt to purge a tag with same name, for instance "el18". 

Could this be solved by adding a namespace to x-cachetag so elements are tagged site1_el18 / site2_el18?

**Comment by ostark** [comment]
Hi Lars,
adding a prefix should be possible with some changes.
Feel free to provide a PR, I'll think of a solution as well.

**Comment by larsboldt** [comment]
Alright, we'll look into it and submit a PR shortly.

**Comment by ostark** [comment]
I'd introduce a helper method at takes care of the concatenation:

```
// Current
Plugin::ELEMENT_PROPERTY_MAP[$prop] . $elementRawQueryResult[$prop];
Plugin::TAG_PREFIX_SECTION . $event->element->sectionId

// New
prepareTag($prop, $elementRawQueryResult[$prop])
prepareTag('sectionId', $event->element->sectionId)
```

Inside that method we can add an additional configurable prefix.

**Comment by kbergha** [comment]
PR @ #20

**Comment by ostark** [comment]
Thank @kbergha. As I mentioned above, your prefix requirement is a good opportunity to clean up the concatenation. I'll take yours and will tweak some things.

**Comment by ostark** [comment]
@kbergha @larsboldt  
Hope my little cleanup session didn't break anything :-)
Feel free to test dev-master.

**Comment by kbergha** [comment]
Look good so far 👍
