### ISSUE TITLE
Disabled entry changed to enabled does not purge cache

### ISSUE THREAD

**Issue by larsboldt** [ostark/upper#19]
If you create an entry with initial state disabled, then later change it to enabled, cache isn't purged it seems.

Is this "as intended" or a bug?

**Comment by ostark** [comment]
Time scheduled entries are not covered so far, but you are talking about disable/enable in the CP, right? Changing the state should trigger purge.

**Comment by larsboldt** [comment]
Entries with a date set to the future seems to purge cache. But if they are set to "Enabled (false)", flag below expiry date, then saved, then you edit and change to "Enabled (true)", cache does not seem to purge properly.

**Comment by larsboldt** [comment]
It might be useful to point out that our context here is a list of entries on a page. We expect the cache of this page to be purged in cache when an entry is published since it should be in this list when its enabled.

**Comment by ostark** [comment]
Ah, okay - but the single Page/Entry gets purged? 

Maybe visibility changes for Entries in lists are not covered so far. I'm not sure if Events are fired in that case. I'll have a look.

By using the [Dummy](https://github.com/ostark/upper/blob/master/src/drivers/Dummy.php) driver, all purge actions are logged. This should help with debugging.

```
UPPER_DRIVER=dummy
```

**Comment by larsboldt** [comment]
The single page / entry page seems to purge yes.

**Comment by ostark** [comment]
You are right, it can't work:

**Comment by ostark** [comment]
@larsboldt @kbergha - Please give (dev-master, unrelease 1.4.0) a try.
