### ISSUE TITLE
Cloudflare api file list limit

### ISSUE THREAD

**Issue by petetak** [ostark/upper#23]
Cloudflare has a 500 url limit for cache invalidation so it would make sense to split the array into smaller chunks and call the api with these chunks.

https://github.com/ostark/upper/blob/b8a584a41d4a85f739770b144d380729fe7f7dd1/src/drivers/Cloudflare.php#L61

I'm happy to work on this and submit a PR but I don't want to change the interface to purgeUrls - ie: I'm not sure what it should return if I made this change.

If you let me know what you would like to do I'll work on it.

**Comment by petetak** [comment]
In face maybe the return value is not important as we are interested only in exceptions from the call to Cloudflare:

https://github.com/ostark/upper/blob/82c23f8c2a872d442e16cf979538303cccdf6405/src/drivers/AbstractPurger.php#L37

So perhaps a decent solution is to chunk the file list and make multiple calls to the Cloudflare api and then return true at the end of it?

**Comment by petetak** [comment]
For example:
https://github.com/supercool/upper/blob/7ef2a4e4a3ad45429d9ac7930219a956d475b598/src/drivers/Cloudflare.php#L62

**Comment by ostark** [comment]
Thanks @petetak - it will take a bit to review your suggestion. Please be patient.

**Comment by petetak** [comment]
No problem at all.  FYI I've put this into production on a site and it's now not getting stuck on cache clear tasks (which it was before) and the upper-cache table is not as huge as it was.

I'll let you know if I run into any issues.

**Comment by petetak** [comment]
That sounds great!
