### ISSUE TITLE
Cloudflare won’t cache without Edge Cache TTL

### ISSUE THREAD

**Issue by joshuabaker** [ostark/upper#24]
I’m trying to get Upper (1.4.2) working with Cloudflare.

Despite seeing `cache-control: public, s-maxage=604800` and `x-upper-cache` headers I’m also getting `cf-cache-status: MISS`.

If I add ‘Edge Cache TTL’ in the Page Rule, alongside ‘Cache Level: Cache Everything’, pages start to cache on the CDN, however, it also means that `cache-control: private, no-cache` is ignored, which messes up the control panel and other dynamic pages.

What might I be missing here?

**Comment by joshuabaker** [comment]
Reading [Cloudflare’s article](https://support.cloudflare.com/hc/en-us/articles/115000150272) on this rule, there’s actually mention of the `Expires` header.

> Cache-Control headers sending "private","no-cache", or "max-age=0" or Expires header with a date in the past will override the rule and cause Cloudflare to NOT cache the resource. To override these you'd need to add another setting called "Edge Cache TTL" and set it to however long you'd like Cloudflare to cache that resource on our servers.

It _looks_ like setting the `Expires` header manually gets a `cf-cache-status: HIT`.

**Comment by joshuabaker** [comment]
Yep. The `Expires` header looks to be culprit here.

Not sure how best to approach this from the plugin perspective. Should Upper set this in [`EventRegistrar.php`](https://github.com/ostark/upper/blob/c65fe43615107fe0ade90fa0c98df996bde851d4/src/EventRegistrar.php#L93)? Considering that `Expires` is ignored by everyone conforming to the RFC it shouldn’t be an issue, right?

**Comment by ostark** [comment]
@joshuabaker Nah, `Cache-Control` works perfectly. 
Can you provide an example? Via private channel, if you like ...

**Comment by ostark** [comment]
```

**Comment by ostark** [comment]
@joshuabaker Doublecheck your "Cache Level" Page Rule
https://github.com/ostark/upper/tree/develop#cloudflare

**Comment by ostark** [comment]
ME: requires further research
