### ISSUE TITLE
Multiple varnish servers

### ISSUE THREAD

**Issue by larsboldt** [ostark/upper#25]
Does Upper support multiple varnish servers?

Can we do `VARNISH_URL=http://1.1.1.1/,http://2.2.2.2` or something?

**Comment by ostark** [comment]
@larsboldt Not yet.
Do you have a real use case for this?

**Comment by larsboldt** [comment]
Yes. We have multiple varnish servers and multiple craft cms backends, so we need this feature. We can submit a PR if you want.

**Comment by larsboldt** [comment]
But we can only test with Varnish ^

**Comment by ostark** [comment]
I'm happy to merge your PR - I never tested varnish properly. 
Also, include a fix for the prefix issue (just remove the second parameter, the default to `-`  should do the trick)

**Comment by larsboldt** [comment]
Alright, will do.

**Comment by ostark** [comment]
Eventually released https://github.com/ostark/upper/commit/48f53b7dadb084ab9764678c53f6db7332cce82c thanks @larsboldt
