### ISSUE TITLE
Bug with keyprefix

### ISSUE THREAD

**Issue by larsboldt** [ostark/upper#26]
`2019-03-04 11:08:04 [-][-][01rarb4pmuca8mloccqut8eoth][error][yii\base\ErrorException:2] yii\base\ErrorException: explode(): Empty delimiter in .../versions/0.3.0/vendor/yiisoft/yii2/helpers/BaseInflector.php:480
Stack trace:
#0 .../versions/0.3.0/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'explode(): Empt...', '...', 480)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'explode(): Empt...', '...', 480, Array)
#2 .../versions/0.3.0/vendor/yiisoft/yii2/helpers/BaseInflector.php(480): explode('', 'dm')
#3 .../versions/0.3.0/vendor/ostark/upper/src/models/Settings.php(109): yii\helpers\BaseInflector::slug('dm', '')
#4 .../versions/0.3.0/vendor/ostark/upper/src/Plugin.php(97): ostark\upper\models\Settings->getKeyPrefix()`

Settings -> getKeyPrefix calls Inflector::slug with empty replacement, replacement is directly used in an explode call in Yii, this fails because its empty. Whether this is a Upper problem or Yii is debatable.

**Comment by ostark** [comment]
@larsboldt Thanks for your report. Which Driver do you use?

**Comment by larsboldt** [comment]
varnish

**Comment by ostark** [comment]
@larsboldt Ah, now I get it.  I'll provide a fix.

**Comment by ostark** [comment]
Eventually released https://github.com/ostark/upper/commit/48f53b7dadb084ab9764678c53f6db7332cce82c thanks @larsboldt
