### ISSUE TITLE
Excluding query string from cache table

### ISSUE THREAD

**Issue by petetak** [ostark/upper#28]
Is there a config option or a way to prevent query string parameters from creating a new entry in the upper_cache table please?

My table is getting full of duplicates and therefore takes much longer to clear.

**Comment by ostark** [comment]
Which "driver" do you use? 
And what's the behaviour of your edge cache? Do you ignore queries strings there?

**Comment by petetak** [comment]
We use Cloudflare.  On Cloudflare we have a blacklist that we can add certain things to like google utm links or other email software ids

**Comment by ostark** [comment]
I'm not happy with the Upper 1.x code base (2.x is WIP and consider to integrate it).
There is no nice way to do it, but this workaround should work for you:

```
<?php 

// config/app.php


return [

    'modules'    => [
       // ...
    ],


    'bootstrap' => [
        function () {
            \yii\base\Event::on(
                \ostark\upper\Plugin::class,
                \ostark\upper\Plugin::EVENT_AFTER_SET_TAG_HEADER,
                function (\ostark\upper\events\CacheResponseEvent $event) {
                    // manipulate requestUrl
                    $event->requestUrl = preg_replace( '/&?utm_.+?(&|$)$/', '', $event->requestUrl );
                },
                null,
                false
            );
        }
    ]
];
```

**Comment by petetak** [comment]
Thanks!

**Comment by ostark** [comment]
@petetak does it work for you?
