### ISSUE TITLE
Ability to add global/default tags

### ISSUE THREAD

**Issue by devinellis** [ostark/upper#30]
We'd like a config value that lets us set one or more site-wide cache tags. This way we can tag everything with `['cms', 'production']`, etc.

We're trying to switch from Varnish to Cloudflare for our HTML caching. However, we run multiple "apps" under our domain and we'd rather not clear all of the Cloudflare cache every time we deploy.

We can take a stab at submitting a PR if you let us know how you would prefer to handle this functionality. One simple solution would be to add the `keyPrefix` as a tag on its own.

Thanks @ostark !

**Comment by ostark** [comment]
Go ahead, some lines of code tell more than 1000 words
