### ISSUE TITLE
Support for multiple Cloudflare domains 

### ISSUE THREAD

**Issue by bwlng** [ostark/upper#32]
Is it possible to clear the cache for multiple Cloudflare zones/domains? I’m using Upper on a Craft install where each site has a different domain. Is there a way to configure multiple zoneIds or domains (such as an array with nested config options under `cloudflare` in `config/upper.php` or arrays for `zoneId` and `domain`)?

**Comment by bwlng** [comment]
Hi Oliver,

Thanks for that info. I will look into a PR and see how far I can take it 😉 

Would you prefer Upper to fire the PurgeEvent and then folks with use cases like mine would listen for the event in their own module?

**Comment by ostark** [comment]
there is no Module required, you can listen directly from you config/app.php using a closure

**Comment by ostark** [comment]
@bwlng Is this still a requirement?

**Comment by bwlng** [comment]
@ostark Yes, I haven’t had a chance to provide a PR, but hope to do so.
