### ISSUE TITLE
[FR] Update Cloudflare driver to use scoped tokens

### ISSUE THREAD

**Issue by tomdavies** [ostark/upper#38]
The CloudFlare driver currently requires the user to use their account level API key, a key which if compromised gives an attacker complete control over their CloudFlare account. Needless to say this is somewhat less than ideal.

As of [August 2019](https://blog.cloudflare.com/api-tokens-general-availability/) CloudFlare allows the creation of scoped tokens than just have the privileges required to clear caches in a zone / domain:

<img width="1114" alt="Screenshot 2020-04-09 09 26 26" src="https://user-images.githubusercontent.com/136308/78874438-4c9ddb80-7a44-11ea-812a-a391b869e040.png">

This is then just passed in a `Authorization: Bearer <token>` header on the CF request in place of the `X-Auth-Key` / `X-Auth-Email` headers.

I appreciate this would be a breaking change for CF users, but it's much more secure, so still seems like a good idea. Perhaps we could support both for now with a deprecation warning for users of `X-Auth-Key`?

Happy to take a stab at a PR if it would be welcome and/or you don't have time @ostark

**Comment by ostark** [comment]
It makes sense to support both, otherwise, a major version bump would be required.
@tomdavies PR?

**Comment by tomdavies** [comment]
Cool, will hop on it this weekend

**Comment by ostark** [comment]
Sorry for the late release https://github.com/ostark/upper/releases/tag/1.6.0
