### ISSUE TITLE
Config setting to truncate header length

### ISSUE THREAD

**Issue by timkelty** [ostark/upper#66]
On large pages, it is possible that the `XKEY/Surrogate-Key/Cache-Tag` exceeds the allowed length of a header by the web server.
IIRC, when this happens, it is generally not handled gracefully and you might get a fatal error from the web server.

I remember when I dealt with this, I had to go an bump the value in nginx _and_ Varnish.

It would be nice if Upper had a config setting to automatically truncate the header, before it was output, to prevent this.

It could have a reasonable default set to whatever nginx or apache uses.

**Comment by ostark** [comment]
https://github.com/ostark/upper/blob/master/src/config.example.php#L25-L30 👀

**Comment by timkelty** [comment]
well then!

**Comment by ostark** [comment]
Adding a reasonable default limit makes sense.
