### ISSUE TITLE
Unable to install on Craft RC6

### ISSUE THREAD

**Issue by torbensko** [ostark/upper#7]
I'm trying to install on both a local and remote instance, as hosted on Heroku. When using the web interface, a message is displayed saying "Couldn’t install plugin." The CLI approach claims to succeed, but the plugin remains disabled in the admin section. I checked the log files, but couldn't find anything of interest. Let me know if I can provide any further detail or if its simply a compatibility issue with the latest Craft version.

**Comment by ostark** [comment]
Thanks for your feedback! I haven't tried RC6 yet, I'll try if I can reproduce it.

**Comment by ostark** [comment]
@torbensko Can you try it again with the latest release? 1.1.2

**Comment by torbensko** [comment]
No luck unfortunately. Of note, I'm using postgres both locally and on Heroku.

**Comment by ostark** [comment]
@torbensko It was [postgres](https://github.com/ostark/upper/commit/c9ec87d81cfaa01cfb4e39719d19f649eba69ee2) related. Thanks for testing! Please pull the latest release.

**Comment by ostark** [comment]
@torbensko `v1.1.3` bypasses the `useLocalTags` option correctly now and `v.1.2.0` adds pgsql support for `useLocalTags`. 

Please give it a try.

**Comment by ostark** [comment]
@torbensko Can you provide the full error message, including the SQL statement?

**Comment by ostark** [comment]
@torbensko Did you have a chance to try again?

**Comment by ostark** [comment]
@torbensko  Did you have a chance to try again?
